version: "1.0"
linter: jetbrains/qodana-python:2024.3
profile:
  name: qodana.recommended
exclude:
  - name: PyPackageRequirementsInspection
  - name: PyUnresolvedReferencesInspection
  - name: DuplicatedCode
